spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
      client:
        config:
          censusClient:
            connect-timeout: 3000
            read-timeout: 12000

census:
  base-url: ${CENSUS_BASE_URL}

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never
